# IMPORTANT!: Use single quotes (''), NOT double quotes ("")!
# All fields must have a value. If a field does not have a value, the config
# will be considered invalid. All fields are required. If you do not have
# a preference for what value a field should get, leave the value provided.

# Version of the config file. Do not change! Automatically updated for each
# config file change
version: '1.0.0'

# Fields for changing the functionality of DuoLogSync (DLS)
dls_settings:
    
  # File where DLS program messages / logs should be saved
  log_filepath: '/tmp/duologsync.log'

  # How Duo logs should be formatted before being sent to a server
  # OPTIONS: CEF, JSON
  log_format: 'JSON'

  # Setting related to API calls for Duo logs
  api:

    # Days in the past from which record retrieval should begin.
    # MINIMUM: 0
    # MAXIMUM: 180
    offset: 180

    # Seconds to wait between API calls (for fetching Duo logs)
    # MINIMUM: 120
    timeout: 120

  # Settings related to saving API call offset information into files for use
  # when DLS crashes so that DLS can pickup where it left off. Useful for
  # reducing the chance of consuming duplicate logs when a crash occurs.
  checkpointing:

    # Whether checkpoint files should be created to save offset information
    # about API calls.
    # OPTIONS: False, True
    enabled: False

    # Directory where checkpoint files should be stored.
    # REQUIRED: if enabled is True
    checkpoint_dir: '/tmp'

# List of servers and how DLS will communicate with them
servers:
  
    # Descriptive name for your server
    # REQUIRED
  - id: ''

    # Address of server to which Duo logs will be sent
    # REQUIRED
    hostname: ''

    # Port of server to which logs will be sent
    # MINIMUM: 0
    # MAXIMUM: 65535
    # REQUIRED
    port: ''

    # Transport protocol used to communicate with the server
    # OPTIONS: TCP, TCPSSL, UDP
    # REQUIRED
    protocol: ''

    # Location of the certificate file used for encrypting communication for
    # TCPSSL
    # REQUIRED: Only if protocol is TCPSSL
    cert_filepath: ''

# To add another server, copy and paste the above, change the server name to
# something unique and descriptive, and fill out the 3 (or 4) fields required
# like so...
# - id:
#   hostname:
#   port:
#   protocol:
#   cert_filepath:

# List of accounts which are used to access Duo logs and tell DLS which logs
# to fetch.
accounts:
  
    # Integration key
    # REQUIRED
  - ikey: ''

    # Private key, keep this safe
    # REQUIRED
    skey: ''

    # Address of the server hosting this account's logs
    # REQUIRED
    hostname: ''
    
    # Here you define to what servers the logs of certain endpoints should go.
    # This is done by creating a mapping (start with dash -) and then defining
    # what endpoints the mapping is for as a list and the what servers apply to
    # those endpoints as a list.
    # ENDPOINTS OPTIONS: adminaction, auth, telephony
    # SERVERS OPTIONS: any server id defined above in the list of servers
    # REQUIRED
    endpoint_server_mappings:
      #- endpoints: ['adminaction', 'auth']
      #  servers: ['Server_1', 'Server_2']
      #- endpoints: ['telephony']
      #  servers: ['Server_1']

    # Whether this account is a Duo MSP account with child accounts. If True,
    # then all the child accounts will be accessed and logs will be pulled for
    # each child account
    # DEFAULT: False
    is_msp: True

    # The child accounts that should not be accessed in the case this account
    # is an MSP account.
    # Only required if is_msp is True and if you need to block accounts from
    # being accessed. It is fine to not include this field
    block_list: []

# To add another account, uncomment the following, change the account name to
# something descriptive and distinct from the other accounts and fill out the
# required  fields
# - ikey:
#   skey:
#   hostname:
#   server:
#   endpoints:
#   parent:
#   block_list:
