duoclient:
  skey: ""
  ikey: ""
  host: ""

logs:
  logDir: "/tmp"
  endpoints:
    enabled: ["auth", "telephony", "adminaction"]
  polling:
    duration: 5
    daysinpast: 180
  checkpointDir: "/tmp"

transport:
  protocol: "TCP"
  host: "localhost"
  port: 8888

recoverFromCheckpoint:
  enabled: False





